### ISSUE TITLE
Visualisieren die Daten

### ISSUE THREAD

**Issue by alayoubiIssam** [JimmyAppel/EntscheidungsunterstuetzungStrom#8]
- [x] Visualisieren auf der Oberfläche die entsprechenden „Prognosewerte“ für einem bestimmten Intervall #9 

- [x] Visualisierung von Strompreisen

- [x] Mehreren Charts/Ansichten #13

- [x] Tabelle für Bewertung die Preise #14
